# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"
Vagrant.configure("2") do |config|

  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "buildserver"
    virtualbox.vm.box = "file://builds/virtualbox-buildserver.box"
    virtualbox.vm.network :public_network, ip: "192.168.99.100"

    config.vm.network "forwarded_port", guest: 8080, host: 8091, id:"http"
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    config.ssh.insert_key = false
    config.vm.synced_folder '.', '/vagrant', type: 'virtualbox'

    virtualbox.vm.provider :virtualbox do |vb|
            vb.gui = false
            vb.memory = 4000
            vb.cpus = 2
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            vb.customize ["modifyvm", :id, "--ioapic", "on"]
            vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
            vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
        end

    config.vm.provision "shell", path: "./scripts/provision.sh"
  end
end