def buildserver='192.168.56.1:8091'
def deployserver='192.168.56.1:8061'

pipeline {
    agent {
        label 'BuildAgent' 
        }
    triggers
   {
    //Any trigger
   }
    stages {
        stage('Clean') {
            steps {
                echo "Clean .........."
                sh 'mvn clean'
            }
        } 
        stage('Build') {
            steps {
                echo "clean, compile and package .........."
                sh 'mvn compile'
            }
        } 
        stage('Run Unit Tests') {
                steps {
                    sh 'mvn resources:testResources compiler:testCompile surefire:test'
                }
                post {
                    always {
                        echo "Archive Junit Surefire test results"
                        junit allowEmptyResults: true, testResults: 'target/surefire-reports/TEST-*.xml'
                    }
                    failure {
                            echo "Trigger mail notifying failed test cases"
                            emailext attachmentsPattern: './target/surefire-reports/TEST-*.xml', body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

Check console output at $BUILD_URL to view the results.''', recipientProviders: [culprits()], subject: 'Test Cases failed !! $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!', to: 'npmahapatra@gmail.com'
                    }
            }
        }
        stage('Package') {
            steps {
                echo "Package .........."
                sh 'mvn -B -DskipTests package'
            }
        }
        
        stage('Generate Documentation/Reporting') {
            steps {
                echo "Generating documentation .........."
                sh 'mvn site'
            }
        }
        post
        {
            always
            {
                publishHTML(target: [reportName: 'Site', reportDir: 'target/site', reportFiles: 'index.html', keepAll: false])
            }
        }
     } 
        stage('Deploy to Build Agent') {
            steps {
                echo "Undeploy and redeploy ... Deploying to Build Agent ........ ${buildserver}"
                sh """ mvn tomcat7:undeploy-only -Dservername="${buildserver}" """
                sh """ mvn tomcat7:deploy-only -Dservername="${buildserver}" """
            }
            post {
                failure {
                            echo "Deploy Site to Build Agent failed"
                        }
            }
        }

        stage('Run Integration tests') {
            steps {
                script {
                    try {
                        echo "Checking if App is live"
                        sh  '''
                        if curl -s --head --request GET http://192.168.56.1:8091/mytestapp/ | grep "HTTP/1.1 200" > /dev/null; then 
                            echo "Website is UP - response 200 OK"
                        else 
                            echo "Website is DOWN"
                            exit 1
                             
                        fi
                        '''
                    } catch(all) {
                        error "failed"
                    }
                }
                //Run some other integration tests here
            }
        }

        stage('Deploy to Deployment Server') {
            steps {
                echo "Undeploy and redeploy..... Deploying to Deployment server ...... ${deployserver}"
                sh """ mvn tomcat7:undeploy-only -Dservername="${deployserver}" """
                sh """ mvn tomcat7:deploy-only -Dservername="${deployserver}" """
            }
            post {
                failure {
                            echo "Deploy Site to Deployment Server failed"
                        }
            }
        }

        stage('Sanity/Load Test') {
            steps {
                script {
                    try {
                        echo "Checking if App is live"
                        sh  '''
                        if curl -s --head --request GET http://192.168.56.1:8061/mytestapp/ | grep "HTTP/1.1 200" > /dev/null; then 
                            echo "Website is UP - response 200 OK"
                        else 
                            echo "Website is DOWN"
                            exit 1 
                        fi
                        '''
                    } catch(all) {
                        error "failed"
                    }
                }
                echo "Run Load tests here...."
                // Load tests go here
            }
        }
    }
}
